HyperTyk/Controllers/LandingController.cs
using HyperTyk.Controllers.Auth;
using HyperTyk.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using static System.Net.WebRequestMethods;

namespace HyperTyk.Controllers
{
    public class LandingController : Controller
    {
        private readonly IAuthenticationService _authenticationService;
        readonly Entities _database = new Entities();

        public LandingController(IAuthenticationService authenticationService)
        {
            _authenticationService = authenticationService;
        }

        // GET: Landing Page
        public ActionResult Index()
        {
            return View();
        }

        // GET: Login Page
        public ActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                var userEmail = User.Identity.Name;

                using (var _database = new Entities()) // Assuming Entities is your DbContext
                {
                    var user = _database.auths.FirstOrDefault(u => u.email == userEmail);

                    if (user != null && user.isbanned == 1)
                    {
                        TempData["ErrorMessage"] = "Seems like your account has been banned. You may contact us or open a ticket!";
                        Session.Clear();
                        FormsAuthentication.SignOut();
                        return View("~/Views/Landing/Auth/Login.cshtml");
                    }

                    var roleName = Session["UserType"];

                    // Original redirection logic based on the role
                    switch (roleName)
                    {
                        case "Admin":
                            return RedirectToAction("Index", "Admin");
                        case "Normal":
                            return RedirectToAction("Index", "Home");
                        default:
                            TempData["ErrorMessage"] = "Your session has expired. Please refresh this page again.";
                            FormsAuthentication.SignOut();
                            Session.Clear();
                            return View("~/Views/Landing/Auth/Login.cshtml");
                    }
                }


                
            }
            return View("~/Views/Landing/Auth/Login.cshtml");
        }

        // GET: Login Page
        public ActionResult Register(string r)
        {
            if (User.Identity.IsAuthenticated)
            {
                var roleName = Session["UserType"];

                switch (roleName)
                {
                    case "Admin":
                        return RedirectToAction("Index", "Admin");
                    case "Normal":
                        return RedirectToAction("Index", "Home");
                    default:
                        return View("~/Views/Landing/Auth/Register.cshtml");
                }

            }
            ViewData["RegistrationCode"] = r;
            return View("~/Views/Landing/Auth/Register.cshtml");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(auth userdatabase, string ReturnUrl)
        {
            var user = await _database.auths.FirstOrDefaultAsync(u => u.username == userdatabase.loginuser || u.email == userdatabase.loginuser);

            if (user != null)
            {
                var account = await _database.accounts
                    .Where(a => a.id == user.id)
                    .Select(a => new
                    {
                        a.id,
                        a.avatar,
                        a.referralcode,
                        a.isverified
                    })
                    .FirstOrDefaultAsync();

                if (account != null)
                {
                    if (AuthPasswordManager.VerifyPassword(userdatabase.password, user.password))
                    {
                        FormsAuthentication.SetAuthCookie(user.email, true);

                        Session["UserId"] = user.id;
                        Session["UserEmail"] = user.email;
                        Session["UserName"] = user.username;
                        Session["UserType"] = user.usertype;
                        Session["AccountAvatar"] = account.avatar;
                        Session["isVerified"] = account.isverified;

                        if (user.isbanned == 1)
                        {
                            TempData["ErrorMessage"] = "Seems like your account has been banned. You may contact us or open a ticket!";
                            Session.Clear();
                            FormsAuthentication.SignOut();
                            return View("~/Views/Landing/Auth/Login.cshtml");
                        }
                        else
                        {
                            if (!string.IsNullOrEmpty(ReturnUrl) && Url.IsLocalUrl(ReturnUrl))
                            {
                                return Redirect(ReturnUrl);
                            }
                            else
                            {
                                switch (user.usertype)
                                {
                                    case "Admin":
                                        return RedirectToAction("Index", "Admin");
                                    case "Normal":
                                        Session["AccountRefCode"] = account.referralcode;
                                        return RedirectToAction("Index", "Home");
                                    default:
                                        TempData["ErrorMessage"] = "Your session has expired. Please log in again.";
                                        FormsAuthentication.SignOut();
                                        Session.Clear();
                                        return View("~/Views/Landing/Auth/Login.cshtml");
                                }
                            }
                        }
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Invalid Email or Password. Please Try Again!";
                        return View("~/Views/Landing/Auth/Login.cshtml");
                    }
                }
            }

            TempData["ErrorMessage"] = "Invalid Email or Password. Please Try Again!";
            return View("~/Views/Landing/Auth/Login.cshtml");
        }

        public byte[] ConvertImageToByteArray(string imagePath)
        {
            string resolvedImagePath = Server.MapPath(imagePath); // Resolve server-side path

            if (!System.IO.File.Exists(resolvedImagePath))
            {
                // Handle file not found (log an error, return null or a default value)
                return null;
            }

            byte[] imageBytes = System.IO.File.ReadAllBytes(resolvedImagePath);
            return imageBytes;
        }

        // POST: Sign Up
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(string username, string email, string password, string referralcode)
        {
            if (_database.auths.Any(a => a.username == username))
            {
                TempData["ErrorMessage"] = "Username already exists.";
                return View("~/Views/Landing/Auth/Register.cshtml");
            }
            else if (username.Length > 12)
            {
                TempData["ErrorMessage"] = "Username cannot exceed 12 characters.";
                return View("~/Views/Landing/Auth/Register.cshtml");
            }

            if (_database.auths.Any(a => a.email == email))
            {
                TempData["ErrorMessage"] = "Email already exists.";
                return View("~/Views/Landing/Auth/Register.cshtml");
            }
            else if (_database.auths.Any(a => a.email.Replace(".", "") == email.Replace(".", "")))
            {
                TempData["ErrorMessage"] = "Email already exists.";
                return View("~/Views/Landing/Auth/Register.cshtml");
            }

            if (ModelState.IsValid)
            {
                string hashedPassword = AuthPasswordManager.HashPassword(password);
                string refcode = AuthReferralCodeManager.GenerateReferralCode();
                byte[] imageBytes = ConvertImageToByteArray("~/Items/9440461.jpg");
                string uuid = AuthUUIDManager.GenerateUUID(username);
                AuthOTPManager otpManager = new AuthOTPManager();
                double coinreward = 0;

                if (!string.IsNullOrEmpty(referralcode))
                {
                    var referredAccount = _database.accounts.FirstOrDefault(a => a.referralcode == referralcode);

                    if (referredAccount != null)
                    {
                        referredAccount.total_users_referred++;

                        if (referredAccount.isverified == 1)
                        {
                            referredAccount.coins += 5;
                            referredAccount.total_coin_earned += 5;

                            coinreward = 2.5;

                            TempData["SuccessMessage"] = $"You have received 2.5 coins as a referral bonus.";
                        }

                        var tableRefLog = new referral_log()
                        {
                            referrer_id = referredAccount.id,
                            referred_id = uuid,
                            referred_email = email,
                            referred_username = username,
                            epochtime = otpManager.GetCurrentEpochTime()
                        };

HyperTyk/Views/Landing/Forgot.cshtml
@model HyperTyk.Models.auth

@{
    ViewBag.Title = "Forgot Password - HyperFyp";
    Layout = "~/Views/Landing/_LandingLayout.cshtml";
}

<style>
    .center-div .inside {
        align-items: unset;
    }

    h2 {
        font-weight: 100;
        margin: 20px 0px 10px 40px;
    }

    .body {
        min-height: 85vh;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

    .login-box {
        max-width: 400px;
        width: 85%;
        margin: 10px auto;
        padding: 40px 20px 40px 20px;
        border: 1px solid #442551;
        border-radius: 10px;
        box-shadow: 0px 5px 10px rgba(0,0,0,0.2);
        background-color: #fafafaff;
        color: #4b2c58;
    }

    .inputbox {
        position: relative;
        margin-bottom: 10px;
        display: flex;
        justify-content: center;
    }

        .inputbox label {
            position: absolute;
            top: -10px;
            left: 5px;
            color: #000000;
            font-size: 1em;
            pointer-events: none;
            transition: .2s;
        }

        .inputbox input {
            width: 90%;
            padding: 15px;
            border: none;
            border-bottom: 2px solid #dcdcdc;
            outline: none;
            border-radius: 15px;
            font-size: 14px;
            background-color: #f4eefb;
            box-sizing: border-box;
        }

            .inputbox input:focus + label, .inputbox input:not(:placeholder-shown) + label {
                bottom: 50px;
                font-size: 14px;
                color: #333;
            }

            .inputbox input:focus, .inputbox input:not(:placeholder-shown) {
                border-bottom-color: #9a00c7;
            }

        .inputbox ion-icon {
            position: absolute;
            right: 35px;
            color: #700079;
            font-size: 1.2em;
            top: 15px;
        }

    .login-button {
        display: flex;
        justify-content: center;
    }

    .button {
        width: 45%;
        height: 49px;
        border-radius: 35px;
        background-color: #5b43a7;
        box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
        border: none;
        outline: none;
        cursor: pointer;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        font-size: 17px;
        font-weight: 500;
        color: #ffffff;
        transition: background-color 0.4s ease;
    }

        .button:hover {
            background-color: #312952;
        }
</style>
<main class="inside">
    <div class="body">
        <div class="login-box">
            <span><i style="font-size: 50px; display: flex; justify-content: center; margin-bottom: 10px;" class='bx bxs-lock'></i></span>
            <span style="color: #4b2c58;font-family: Bahnschrift;font-weight: 900; font-size: 30px; display: flex; justify-content: center;">Trouble Logging In?</span>
            <h5 style="text-align: center; display: flex; justify-content: center; margin-bottom: 30px; ">Enter your username or email and we'll send <br /> you a 6-digit OTP to get back into your account.</h5>
            <section>
                @using (Html.BeginForm("Forgot", "Landing", FormMethod.Post))
                {
                    <div class="inputbox">
                        @Html.EditorFor(model => model.loginuser, new { htmlAttributes = new { @class = "inputbox", @placeholder = "Username or E-mail Address", @name = "user", @id = "user", @required = "required", @type = "text" } })
                    </div>
                    <br />
                    <div class="login-button">
                        <button type="submit" class="button" id="post">Continue</button>
                    </div>
                    <div style="display: flex; justify-content: center; font-weight: 500; font-size: 15px; margin-top: 15px;">
                        <p style="color: black">Are you already aware of your password? <a style="color:blueviolet;" href="@Url.Action("login", "Landing")">Log In</a></p>
                    </div>
                }
            </section>
        </div>
    </div>
</main>
<script>
    window.onload = function () {
        var errorAlert = document.getElementById('passwordMismatch');
        var successAlert = document.getElementById('passwordMismatch2');

        function hideNotification(notification) {
            var container = notification.parentElement;
            container.style.animation = 'slideOut 0.5s ease forwards';
            container.addEventListener('animationend', function () {
                container.style.display = 'none';
            });
        }

        if (errorAlert) {
            errorAlert.querySelector('.close').addEventListener('click', function () {
                hideNotification(errorAlert);
            });
            setTimeout(function () {
                hideNotification(errorAlert);
            }, 4000);
        } else if (successAlert) {
            successAlert.querySelector('.close').addEventListener('click', function () {
                hideNotification(successAlert);
            });
            setTimeout(function () {
                hideNotification(successAlert);
            }, 4000);
        }
    };
</script>

HyperTyk/Views/Landing/Index.cshtml
@{
    ViewBag.Title = "HyperFyp";
    Layout = "~/Views/Landing/_LandingLayout.cshtml";
}
<style>
    .body {
        width: 100%;
    }

    .body-2 {
        height: auto;
        text-align: center;
        padding: 50px;
        display: flex;
        justify-content: center;
        background-color: #51007c;
        gap: 20px;
        flex-wrap: wrap;
    }

    .body-3 {
        height: 100vh;
        padding: 70px 15px 20px 15px;
        display: flex;
        flex-direction: column;
        background-color: #51007c;
    }

    .front-buttons {
        display: flex;
        justify-content: center;
        gap: 20px;
        flex-wrap: wrap;
    }

    a {
        text-decoration: none;
        color: white;
        font-weight: 800;
    }

    .button {
        background-color: #df37f1;
        padding: 10px 20px;
        border-radius: 15px;
        display: flex;
        align-items: center;
        gap: 5px;
        transition: all 0.2s ease-in-out;
        cursor: pointer;
    }

    .pink {
        background-color: #51007c;
    }

    .button:hover {
        box-shadow: 0 0 10px #f6a1ff;
        background-color: #ce79d8;
        gap: 10px;
    }

    .body-2-content {
        width: 300px;
        height: 350px;
        color: black;
        padding: 10px;
        background-color: #c789f8bc;
        display: flex;
        justify-content: space-evenly;
        flex-direction: column;
        border: 3px solid;
        border-image: linear-gradient(to right, red, cyan);
        border-image-slice: 1;
        cursor: pointer;
        transition: all 0.3s ease-in-out; /* General transitions */
    }

        .body-2-content:hover {
            background-color: #51007c;
            color: #fff;
            transition: background 0.3s ease-in-out; /* Specific background transition */
        }

    .text-shadow {
        position: absolute;
        right: 2.5px;
        color: #ff0000ff;
    }

    .text-shadow-2 {
        position: absolute;
        left: 2.5px;
        color: #00ffde;
    }

    .text-shadow-3 {
        position: absolute;
        left: 0px;
        color: #000000;
    }

</style>
<main class="inside">   
    <div class="body">
        <div class="body-1">
            <h1>Become famous on <span id="typing">Social Media!</span></h1>
            <h2>Get your free views today!</h2>
            <h3>FAST, EASY AND FREE!</h3>
            <br /><br />
            <div class="front-buttons">
                <a href="@Url.Action("register", "Landing")" class="button">Start hyping! <i class='bx bx-chevrons-right'></i></a>
                <a class="button pink">Tips to Grow</a>
            </div>
        </div>
        <div class="body-2">
            <div class="body-2-content">
                <div class="body-2-title">
                    <span style="font-family: 'Poppins', sans-serif; font-size: 60px; font-weight: 800; position: relative;">
                        <span>FREE</span>
                        <span class="text-shadow">FREE</span>
                        <span class="text-shadow-2">FREE</span>
                        <span class="text-shadow-3">FREE</span>
                    </span>
                </div>
                <div class="body-2-desc">
                    HyperFyp offers free boosting to help you grow your account, prank friends, and much more!
                    All this for free!
                </div>
            </div>
            <div class="body-2-content">
                <div class="body-2-title">
                    <span style="font-family: 'Poppins', sans-serif; font-size: 60px; font-weight: 800; position: relative;">
                        <span>FAST</span>
                        <span class="text-shadow">FAST</span>
                        <span class="text-shadow-2">FAST</span>
                        <span class="text-shadow-3">FAST</span>
                    </span>
                </div>
                <div class="body-2-desc">
                    All orders instantly starts, process takes about 10 minutes!
                </div>
            </div>
            <div class="body-2-content">
                <div class="body-2-title">
                    <span style="font-family: 'Poppins', sans-serif; font-size: 60px; font-weight: 800; position: relative;">
                        <span>EASY</span>
                        <span class="text-shadow">EASY</span>
                        <span class="text-shadow-2">EASY</span>
                        <span class="text-shadow-3">EASY</span>
                    </span>
                </div>
                <div class="body-2-desc">
                    With our easy interface, it was never so easy to become famous! What are you waiting for? Start Today!
                </div>
            </div>
        </div>
        @*<div class="body-3">
            <span style="text-align: center; font-family: 'Poppins', sans-serif; font-size: 60px; font-weight: 800;">About Us</span>
            <div style="height: 80%; padding: 50px; border-radius: 15px; border: 4px solid #f6a1ff;">
            </div>
        </div>*@
    </div>
</main>

<script>
    const socialMediaPlatforms = [
        { name: 'Facebook!' },
        { name: 'TikTok!' },
        { name: 'Instagram!' }
    ];

    const typingElement = document.getElementById('typing');
    let currentPlatformIndex = 0;
    let currentLetterIndex = 0;
    let isDeleting = false;

    function typePlatforms() {
        const platform = socialMediaPlatforms[currentPlatformIndex];
        const platformName = platform.name;

        const fullText = isDeleting ? platformName.slice(0, currentLetterIndex) : platformName.slice(0, currentLetterIndex + 1);

        typingElement.innerHTML = `${fullText}`;

        if (!isDeleting && currentLetterIndex === platformName.length) {
            isDeleting = true;
            setTimeout(typePlatforms, 1500); // Wait after typing complete
        } else if (isDeleting && currentLetterIndex === 0) {
            isDeleting = false;
            currentPlatformIndex = (currentPlatformIndex + 1) % socialMediaPlatforms.length;
            setTimeout(typePlatforms, 500); // Delay before typing next platform
        } else {
            setTimeout(typePlatforms, isDeleting ? 100 : 300); // Typing speed: 200 milliseconds, Deleting speed: 100 milliseconds
        }

        currentLetterIndex = isDeleting ? currentLetterIndex - 1 : currentLetterIndex + 1;
    }

    typePlatforms();
</script>

HyperTyk/Views/Landing/OTP.cshtml
@{
    ViewBag.Title = "One Time Password - HyperFyp";
    Layout = "~/Views/Landing/_LandingLayout.cshtml";
}
<style>
    .center-div .inside {
        align-items: unset;
    }

    h2 {
        font-weight: 100;
        margin: 20px 0px 10px 40px;
    }

    .body {
        min-height: 85vh;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    .login-box {
        max-width: 400px;
        width: 85%;
        margin: 10px auto;
        padding: 40px 35px;
        border: 1px solid #442551;
        border-radius: 10px;
        box-shadow: 0px 5px 10px rgba(0,0,0,0.2);
        background-color: #fafafaff;
        color: #4b2c58;
    }

    .inputbox {
        position: relative;
        margin-bottom: 10px;
        display: flex;
        justify-content: center;
    }

        .inputbox label {
            position: absolute;
            top: -10px;
            left: 5px;
            color: #000000;
            font-size: 1em;
            pointer-events: none;
            transition: .2s;
        }

        .inputbox input {
            width: 90%;
            padding: 15px;
            border: none;
            border-bottom: 2px solid #dcdcdc;
            outline: none;
            border-radius: 15px;
            font-size: 14px;
            background-color: #f4eefb;
            box-sizing: border-box;
        }

            .inputbox input:focus + label, .inputbox input:not(:placeholder-shown) + label {
                bottom: 50px;
                font-size: 14px;
                color: #333;
            }

            .inputbox input:focus, .inputbox input:not(:placeholder-shown) {
                border-bottom-color: #9a00c7;
            }

        .inputbox ion-icon {
            position: absolute;
            right: 35px;
            color: #700079;
            font-size: 1.2em;
            top: 15px;
        }

    .login-button {
        display: flex;
        justify-content: center;
    }

    .button {
        width: 45%;
        height: 49px;
        border-radius: 35px;
        background-color: #5b43a7;
        box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
        border: none;
        outline: none;
        cursor: pointer;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        font-size: 17px;
        font-weight: 500;
        color: #ffffff;
        transition: background-color 0.4s ease;
    }

        .button:hover {
            background-color: #312952;
        }

    .pin-inputs {
        display: flex;
        justify-content: center;
        gap: 10px;
        margin-bottom: 40px;
    }

        .pin-inputs .pin-input {
            -moz-appearance: textfield;
            width: 50px;
            height: 60px;
            text-align: center;
            font-size: 1.2rem;
            padding: 15px;
            border: none;
            border-bottom: 2px solid #dcdcdc;
            border-radius: 15px;
            background-color: #d8d1e0;
            box-sizing: border-box;
        }

    .pin-input::placeholder {
        color: #8e8e8e87;
    }

    .pin-input::-webkit-outer-spin-button, .pin-input::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    .pin-input:focus, .pin-input:not(:placeholder-shown) {
        border-bottom-color: #5b43a7;
    }
</style>
<main class="inside">
    <div class="body">
        <div class="login-box">
            <span><i style="font-size: 50px; display: flex; justify-content: center;" class='bx bxs-check-shield'></i></span>
            <span style="margin-top: 20px;color: #4b2c58;font-family: Bahnschrift;font-weight: 900; font-size: 30px; display: flex; justify-content: center;">One-Time Password<br /></span>
            <h5 style="display: flex; justify-content: center; margin-bottom:45px;">Enter the 6-digit PIN from your email.</h5>
            @using (Html.BeginForm("OTP", "Landing", FormMethod.Post, new { @onsubmit = "autoCombineOTP()" }))
            {
                @Html.AntiForgeryToken()
                <div class="pin-inputs">
                    @for (int i = 0; i < 6; i++)
                    {
                        @Html.TextBox("pin" + i, null, new { @class = "pin-input", @type = "number", @autocomplete = "off", @oninput = "limitToSingleNumber(this);", @onkeyup = "autoTab(this, event);", @required = "required" })
                    }
                    @Html.Hidden("enteredOTP", null, new { @id = "combinedOTP" })
                </div>
                <div class="login-button">
                    <button type="submit" class="button" id="post">Verify</button>
                </div>
            }
            <section>
            </section>
        </div>
    </div>
</main>
<script>
    window.onload = function () {
        var errorAlert = document.getElementById('passwordMismatch');
        var successAlert = document.getElementById('passwordMismatch2');

        function hideNotification(notification) {
            var container = notification.parentElement;
            container.style.animation = 'slideOut 0.5s ease forwards';
            container.addEventListener('animationend', function () {
                container.style.display = 'none';
            });
        }

        if (errorAlert) {
            errorAlert.querySelector('.close').addEventListener('click', function () {
                hideNotification(errorAlert);
            });
            setTimeout(function () {
                hideNotification(errorAlert);
            }, 4000);
        } else if (successAlert) {
            successAlert.querySelector('.close').addEventListener('click', function () {
                hideNotification(successAlert);
            });
            setTimeout(function () {
                hideNotification(successAlert);
            }, 4000);
        }
    };
</script>
<script>
    function limitToSingleNumber(input) {
        input.value = input.value.replace(/\D/g, '');
        if (input.value.length > 1) {
            input.value = input.value.substring(0, 1);
        }
    }
    function autoTab(current, event) {
        if (event.keyCode === 8 || event.keyCode === 46) {
            if (current.value.length === 0) {
                var prevInput = $(current).prev('.pin-input');
                if (prevInput.length > 0) {
                    prevInput.focus();
                }
            }
        }
        else if (current.value.length >= current.maxLength) {
            var nextInput = $(current).next('.pin-input');
            if (nextInput.length > 0) {
                nextInput.focus();
            }
        }
    }
    function autoCombineOTP() {
        $('#loadingScreen').show();
        var otp = '';
        for (var i = 0; i < 6; i++) {
            otp += $('#pin' + i).val();
        }
        $('#combinedOTP').val(otp);
        document.getElementById("otpForm").submit();


    }
</script>